/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;
import com.sun.imageio.plugins.jpeg.JPEG;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Luis Vidal
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void OpenInternet() {
        try {
            Desktop.getDesktop().browse(URI.create("https://www.google.com/"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void jPanelXRight(final int start, final int stop, final int delay, final int increment, final JPanel JPanel) {
        if (JPanel.getX() == start) {
            new Thread() {
                public void run() {
                    while (JPanel.getX() <= start) {
                        for (int i = start; i <= stop; i += increment) {
                            try {
                                Thread.sleep(delay);

                                JPanel.setLocation(i, JPanel.getY());
                            } catch (InterruptedException e) {
                                System.out.println("Error Thread Interrupted: " + e);
                            }
                        }
                    }
                    JPanel.setLocation(stop, JPanel.getY());
                }
            }.start();
        }
    }

    public void jPanelXLeft(final int start, final int stop, final int delay, final int increment, final JPanel JPanel) {
        if (JPanel.getX() == start) {
            new Thread() {
                public void run() {
                    while (JPanel.getX() > stop) {
                        for (int i = start; i >= stop; i -= increment) {
                            try {
                                Thread.sleep(delay);
                                JPanel.setLocation(i, JPanel.getY());
                            } catch (InterruptedException e) {
                                System.out.println("Error Thread Interrupted: " + e);
                            }
                        }
                    }
                    JPanel.setLocation(stop, JPanel.getY());
                }
            }.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jlblSocios1 = new javax.swing.JLabel();
        jlblSocios = new javax.swing.JLabel();
        jlblEventos = new javax.swing.JLabel();
        jlblAnota = new javax.swing.JLabel();
        lblCronograma1 = new javax.swing.JLabel();
        lblDrive = new javax.swing.JLabel();
        jbtnIdea = new javax.swing.JLabel();
        jlblDrive = new javax.swing.JLabel();
        jbtnAlarma = new javax.swing.JLabel();
        jbtnAjustes = new javax.swing.JLabel();
        jbtnCalendario = new javax.swing.JLabel();
        jbtnSaludo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jbtnInternet3 = new javax.swing.JLabel();
        jlblRegistroCorrecto = new javax.swing.JLabel();
        jpRegister = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jlblNext = new javax.swing.JLabel();
        jpIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jpswPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlblInternet = new javax.swing.JLabel();
        jlblCalculadora = new javax.swing.JLabel();
        jlblMusica = new javax.swing.JLabel();
        jpBar = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1050, 575));
        setMaximumSize(new java.awt.Dimension(1050, 575));
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1050, 575));
        getContentPane().setLayout(null);

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setForeground(new java.awt.Color(255, 255, 255));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSocios1.setBackground(new java.awt.Color(255, 99, 71));
        jlblSocios1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblSocios1.setForeground(new java.awt.Color(255, 99, 71));
        jlblSocios1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSocios1.setText("Ajustes");
        jpMenu.add(jlblSocios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 130, 30));

        jlblSocios.setBackground(new java.awt.Color(255, 99, 71));
        jlblSocios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblSocios.setForeground(new java.awt.Color(255, 99, 71));
        jlblSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSocios.setText("Socios");
        jpMenu.add(jlblSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 130, 30));

        jlblEventos.setBackground(new java.awt.Color(255, 99, 71));
        jlblEventos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblEventos.setForeground(new java.awt.Color(255, 99, 71));
        jlblEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEventos.setText("Eventos");
        jpMenu.add(jlblEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 30));

        jlblAnota.setBackground(new java.awt.Color(255, 99, 71));
        jlblAnota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblAnota.setForeground(new java.awt.Color(255, 99, 71));
        jlblAnota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAnota.setText("Anotaciones");
        jpMenu.add(jlblAnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 130, 30));

        lblCronograma1.setBackground(new java.awt.Color(255, 99, 71));
        lblCronograma1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCronograma1.setForeground(new java.awt.Color(255, 99, 71));
        lblCronograma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronograma1.setText("Cronograma");
        jpMenu.add(lblCronograma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 130, 30));

        lblDrive.setBackground(new java.awt.Color(255, 99, 71));
        lblDrive.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDrive.setForeground(new java.awt.Color(255, 99, 71));
        lblDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrive.setText("Drive");
        jpMenu.add(lblDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 30));

        jbtnIdea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnIdea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Idea_96px.png"))); // NOI18N
        jbtnIdea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnIdea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnIdeaMouseMoved(evt);
            }
        });
        jbtnIdea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnIdeaMouseExited(evt);
            }
        });
        jpMenu.add(jbtnIdea, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 190, 170));

        jlblDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Google_Drive_96px.png"))); // NOI18N
        jlblDrive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblDrive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlblDriveMouseMoved(evt);
            }
        });
        jlblDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblDriveMouseExited(evt);
            }
        });
        jpMenu.add(jlblDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, 170));

        jbtnAlarma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnAlarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Clock_96px.png"))); // NOI18N
        jbtnAlarma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAlarma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnAlarmaMouseMoved(evt);
            }
        });
        jbtnAlarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAlarmaMouseExited(evt);
            }
        });
        jpMenu.add(jbtnAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 190, 170));

        jbtnAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Maintenance_96px.png"))); // NOI18N
        jbtnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAjustes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnAjustesMouseMoved(evt);
            }
        });
        jbtnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAjustesMouseExited(evt);
            }
        });
        jpMenu.add(jbtnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 190, 170));

        jbtnCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Today_96px.png"))); // NOI18N
        jbtnCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCalendario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnCalendarioMouseMoved(evt);
            }
        });
        jbtnCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCalendarioMouseExited(evt);
            }
        });
        jpMenu.add(jbtnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 170));

        jbtnSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnSaludo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Handshake_96px.png"))); // NOI18N
        jbtnSaludo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSaludo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnSaludoMouseMoved(evt);
            }
        });
        jbtnSaludo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnSaludoMouseExited(evt);
            }
        });
        jpMenu.add(jbtnSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 190, 170));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Copyright WriteCode");
        jpMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 140, -1));

        jtxtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jtxtBuscar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jtxtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBuscar.setText("Busca una opción");
        jtxtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jtxtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBuscarMouseClicked(evt);
            }
        });
        jpMenu.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 230, 30));

        jbtnInternet3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32px_2.png"))); // NOI18N
        jpMenu.add(jbtnInternet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, -1));

        jlblRegistroCorrecto.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jlblRegistroCorrecto.setForeground(new java.awt.Color(255, 99, 71));
        jlblRegistroCorrecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblRegistroCorrecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblRegistroCorrectoMouseClicked(evt);
            }
        });
        jpMenu.add(jlblRegistroCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 220, 20));

        getContentPane().add(jpMenu);
        jpMenu.setBounds(290, 50, 760, 530);

        jpRegister.setBackground(new java.awt.Color(255, 255, 255));
        jpRegister.setForeground(new java.awt.Color(255, 255, 255));
        jpRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Decker", 0, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 99, 71));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Register_");
        jpRegister.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 210, 90));

        jLabel10.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Nombres:");
        jpRegister.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jpRegister.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 280, 50));

        jLabel11.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Apellidos:");
        jpRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 153, 153));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jpRegister.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 280, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpRegister.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 50, 330));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 153, 153));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jpRegister.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 280, 50));

        jLabel12.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Carrera:");
        jpRegister.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 153, 153));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jpRegister.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 280, 50));

        jLabel13.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("E-mail:");
        jpRegister.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jtxtUser.setBackground(new java.awt.Color(204, 204, 204));
        jtxtUser.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jtxtUser.setForeground(new java.awt.Color(255, 153, 153));
        jtxtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jpRegister.add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 280, 50));

        jLabel14.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Usuario:");
        jpRegister.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Decker", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Contraseña:");
        jpRegister.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jpRegister.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 280, 50));

        jlblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Next_page_64px.png"))); // NOI18N
        jlblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblNext.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlblNextMouseMoved(evt);
            }
        });
        jlblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblNextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblNextMouseExited(evt);
            }
        });
        jpRegister.add(jlblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 70, 60));

        getContentPane().add(jpRegister);
        jpRegister.setBounds(1050, 50, 760, 530);

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_96px_2.png"))); // NOI18N
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, 80));

        jtxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jtxtUsuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jtxtUsuario.setText("Ingrese usuario..");
        jtxtUsuario.setBorder(null);
        jtxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtUsuarioMouseClicked(evt);
            }
        });
        jpIngreso.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, 40));

        jpswPass.setBackground(new java.awt.Color(255, 255, 255));
        jpswPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jpswPass.setForeground(new java.awt.Color(153, 153, 153));
        jpswPass.setText("Contrasena");
        jpswPass.setBorder(null);
        jpswPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpswPassMouseClicked(evt);
            }
        });
        jpIngreso.add(jpswPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 170, 40));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("PASSWORD:");
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("USER:");
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, -1));
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 190, 20));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 190, 20));

        jLabel6.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 99, 71));
        jLabel6.setText("Not yet a member?");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jpIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 490, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_customer_32px_1.png"))); // NOI18N
        jpIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jpIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 130, 40));

        jlblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        jlblInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblInternetMouseClicked(evt);
            }
        });
        jpIngreso.add(jlblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 120, 30, -1));

        jlblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        jlblCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCalculadoraMouseClicked(evt);
            }
        });
        jpIngreso.add(jlblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 160, 30, -1));

        jlblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Musical_Notes_32px.png"))); // NOI18N
        jlblMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMusicaMouseClicked(evt);
            }
        });
        jpIngreso.add(jlblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 200, 30, -1));

        getContentPane().add(jpIngreso);
        jpIngreso.setBounds(0, 0, 290, 580);

        jpBar.setBackground(new java.awt.Color(255, 255, 255));
        jpBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jpBar.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jpBar.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 30));

        getContentPane().add(jpBar);
        jpBar.setBounds(290, 0, 760, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jPanelXRight(290, 1050, 20, 10, jpMenu);
        jPanelXLeft(1050, 290, 20, 10, jpRegister);

        //<----//
        jPanelXLeft(1050, 290, 20, 10, jpMenu);
        jPanelXRight(290, 1050, 20, 10, jpRegister);
        
        jlblRegistroCorrecto.setText("");

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jlblDriveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDriveMouseMoved
        jlblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jlblDriveMouseMoved

    private void jlblDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDriveMouseExited
        jlblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jlblDriveMouseExited

    private void jbtnAlarmaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAlarmaMouseMoved
        jbtnAlarma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jbtnAlarmaMouseMoved

    private void jbtnAlarmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAlarmaMouseExited
        jbtnAlarma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jbtnAlarmaMouseExited

    private void jbtnIdeaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIdeaMouseMoved
        jbtnIdea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jbtnIdeaMouseMoved

    private void jbtnIdeaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIdeaMouseExited
        jbtnIdea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jbtnIdeaMouseExited

    private void jbtnCalendarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCalendarioMouseMoved
        jbtnCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jbtnCalendarioMouseMoved

    private void jbtnCalendarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCalendarioMouseExited
        jbtnCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jbtnCalendarioMouseExited

    private void jbtnSaludoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaludoMouseMoved
        jbtnSaludo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jbtnSaludoMouseMoved

    private void jbtnSaludoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaludoMouseExited
        jbtnSaludo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jbtnSaludoMouseExited

    private void jbtnAjustesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjustesMouseMoved
        jbtnAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jbtnAjustesMouseMoved

    private void jbtnAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjustesMouseExited
        jbtnAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jbtnAjustesMouseExited

    private void jtxtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBuscarMouseClicked
        jtxtBuscar.setText("");
    }//GEN-LAST:event_jtxtBuscarMouseClicked

    private void jtxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUsuarioMouseClicked
        jtxtUsuario.setText("");
    }//GEN-LAST:event_jtxtUsuarioMouseClicked

    private void jpswPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswPassMouseClicked
        jpswPass.setText("");
    }//GEN-LAST:event_jpswPassMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        int dialogButon = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir del login?", "EXIT", dialogButon);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-30, 0, 10, 5, jlblInternet);

        AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXRight(-30, 0, 10, 5, jlblCalculadora);

        AnimationClass reproductor = new AnimationClass();
        reproductor.jLabelXRight(-30, 0, 10, 5, jlblMusica);

        //<-------
        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(0, -30, 10, 5, jlblInternet);

        AnimationClass calculadoraa = new AnimationClass();
        calculadoraa.jLabelXLeft(0, -30, 10, 5, jlblCalculadora);

        AnimationClass reproductorr = new AnimationClass();
        reproductorr.jLabelXLeft(0, -30, 10, 5, jlblMusica);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jlblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblInternetMouseClicked
        OpenInternet();
    }//GEN-LAST:event_jlblInternetMouseClicked

    private void jlblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCalculadoraMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }//GEN-LAST:event_jlblCalculadoraMouseClicked

    private void jlblMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMusicaMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("Spotify");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }//GEN-LAST:event_jlblMusicaMouseClicked

    private void jlblNextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNextMouseMoved
        jlblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Next_page_64px_1.png")));
    }//GEN-LAST:event_jlblNextMouseMoved

    private void jlblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNextMouseExited
        jlblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Next_page_64px.png")));
    }//GEN-LAST:event_jlblNextMouseExited

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jlblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNextMouseClicked
        jPanelXRight(290, 1050, 20, 10, jpMenu);
        jPanelXLeft(1050, 290, 20, 10, jpRegister);

        //<----//
        jPanelXLeft(1050, 290, 20, 10, jpMenu);
        jPanelXRight(290, 1050, 20, 10, jpRegister);
        
        jlblRegistroCorrecto.setText("Usuario "+jtxtUser.getText()+" correctamente!");
    }//GEN-LAST:event_jlblNextMouseClicked

    private void jlblRegistroCorrectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblRegistroCorrectoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblRegistroCorrectoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jbtnAjustes;
    private javax.swing.JLabel jbtnAlarma;
    private javax.swing.JLabel jbtnCalendario;
    private javax.swing.JLabel jbtnIdea;
    private javax.swing.JLabel jbtnInternet3;
    private javax.swing.JLabel jbtnSaludo;
    private javax.swing.JLabel jlblAnota;
    private javax.swing.JLabel jlblCalculadora;
    private javax.swing.JLabel jlblDrive;
    private javax.swing.JLabel jlblEventos;
    private javax.swing.JLabel jlblInternet;
    private javax.swing.JLabel jlblMusica;
    private javax.swing.JLabel jlblNext;
    private javax.swing.JLabel jlblRegistroCorrecto;
    private javax.swing.JLabel jlblSocios;
    private javax.swing.JLabel jlblSocios1;
    private javax.swing.JPanel jpBar;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpRegister;
    private javax.swing.JPasswordField jpswPass;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtUser;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.JLabel lblCronograma1;
    private javax.swing.JLabel lblDrive;
    // End of variables declaration//GEN-END:variables
}
